Repository rustcoreutils/posixutils-rs, pull requests merged in 2024-07, with the labels that each got.

#155 who and uname updates
  README.md
  sys/src/uname.rs
  sys/src/who.rs
Labels: enhancement

#156 dd improvements
  file/src/dd.rs
  file/tests/dd-tests.rs
  file/tests/dd.ascii
  file/tests/dd.ebcdic
  file/tests/dd.ibm
  file/tests/dd.lcase
  file/tests/dd.swab
  file/tests/dd.ucase
  plib/src/testing.rs
Labels: enhancement

#157 dd work
  file/src/dd.rs
  file/tests/dd-tests.rs
Labels: enhancement

#158 More dd work
  file/src/dd.rs
  file/tests/dd-tests.rs
  file/tests/dd.block
  file/tests/dd.sync
  file/tests/dd.unblock
  file/tests/dd_test_input.txt
Labels: enhancement

#162 Test suite additions (and bug fixes)
  Cargo.lock
  README.md
  calc/tests/bc-tests.rs
  calc/tests/expr-tests.rs
  display/tests/echo-tests.rs
  display/tests/printf-tests.rs
  pathnames/src/basename.rs
  pathnames/src/dirname.rs
  pathnames/tests/basename-tests.rs
  pathnames/tests/dirname-tests.rs
  tree/Cargo.toml
  tree/src/readlink.rs
  tree/tests/readlink-tests.rs
Labels: bug, enhancement

#163 More testing work. Some fixes.
  README.md
  text/src/comm.rs
  text/tests/comm-tests.rs
  text/tests/comm/comm.0
  text/tests/comm/comm.1
  text/tests/comm/comm.2
  text/tests/comm/comm.3
  text/tests/comm/comm.file1
  text/tests/comm/comm.file2
  text/tests/csplit-tests.rs
  text/tests/cut-tests.rs
  text/tests/diff-tests.rs
  text/tests/expand-tests.rs
  text/tests/head-tests.rs
  text/tests/integration.rs
  text/tests/nl-tests.rs
  text/tests/pr-tests.rs
  text/tests/sort-tests.rs
  text/tests/tail-tests.rs
  text/tests/tr-tests.rs
  text/tests/unexpand-tests.rs
  text/tests/uniq-tests.rs
  text/tests/wc-tests.rs
  tree/tests/cp-tests.rs
  tree/tests/ls-tests.rs
  tree/tests/mv-tests.rs
  tree/tests/rm-tests.rs
Labels: bug, enhancement

#164 Moar test work
  README.md
  file/tests/dd-tests.rs
  file/tests/dd/dd.ascii
  file/tests/dd/dd.block
  file/tests/dd/dd.ebcdic
  file/tests/dd/dd.ibm
  file/tests/dd/dd.lcase
  file/tests/dd/dd.swab
  file/tests/dd/dd.sync
  file/tests/dd/dd.ucase
  file/tests/dd/dd.unblock
  file/tests/dd/dd_test_input.txt
  text/src/fold.rs
  text/tests/expand-tests.rs
  text/tests/fold-tests.rs
  text/tests/fold/input1.txt
  text/tests/fold/input2.txt
  text/tests/fold/output_bytes.txt
  text/tests/fold/output_bytes_spaces.txt
  text/tests/fold/output_default.txt
  text/tests/fold/output_spaces.txt
  text/tests/fold/output_width40.txt
  text/tests/paste-tests.rs
  text/tests/paste/input1.txt
  text/tests/paste/input2.txt
  text/tests/paste/input3.txt
  text/tests/paste/output_custom_delim.txt
  text/tests/paste/output_default.txt
  text/tests/paste/output_serial.txt
  text/tests/paste/output_serial_custom_delim.txt
  text/tests/pr-tests.rs
  text/tests/tr-tests.rs
  text/tests/uniq-tests.rs
  text/tests/wc-tests.rs
Labels: enhancement, cleanup

#165 Continued test suite work
  README.md
  plib/src/modestr.rs
  tree/src/link.rs
  tree/src/unlink.rs
  tree/tests/link-tests.rs
  tree/tests/mkdir-tests.rs
  tree/tests/rmdir-tests.rs
  tree/tests/unlink-tests.rs
  xform/tests/integration.rs
Labels: bug, enhancement

#166 add util: Getconf
  README.md
  TODO.md
  sys/Cargo.toml
  sys/src/getconf.rs
  sys/tests/getconf-tests.rs
Labels: enhancement

#167 Sccs: what
  Cargo.lock
  Cargo.toml
  plib/src/lib.rs
  plib/src/sccsfile.rs
  sccs/Cargo.toml
  sccs/src/what.rs
  sccs/tests/empty_file.txt
  sccs/tests/multiple_identifications.txt
  sccs/tests/no_identification.txt
  sccs/tests/single_identification.txt
  sccs/tests/single_identification_flag.txt
  sccs/tests/special_characters.txt
  sccs/tests/what-tests.rs
Labels: enhancement

#168 Modularize test suite
  calc/tests/bc/mod.rs
  calc/tests/calc-tests.rs
  calc/tests/expr/mod.rs
  dev/tests/dev-tests.rs
  display/tests/display-tests.rs
  display/tests/echo/mod.rs
  display/tests/printf/mod.rs
  file/tests/cmp/mod.rs
  file/tests/dd/mod.rs
  file/tests/file-tests.rs
  file/tests/file/mod.rs
  file/tests/integration.rs
  file/tests/od/mod.rs
  misc/tests/false/mod.rs
  misc/tests/misc-tests.rs
  misc/tests/test/mod.rs
  misc/tests/true/mod.rs
  pathnames/tests/basename/mod.rs
  pathnames/tests/dirname/mod.rs
  pathnames/tests/pathnames-tests.rs
  process/tests/process-tests.rs
  process/tests/xargs/mod.rs
  sccs/tests/sccs-tests.rs
  sccs/tests/what/mod.rs
  sys/tests/getconf/mod.rs
  sys/tests/sys-tests.rs
  text/tests/comm/mod.rs
  text/tests/csplit/mod.rs
  text/tests/cut/mod.rs
  text/tests/expand/mod.rs
  text/tests/fold/mod.rs
  text/tests/head/mod.rs
  text/tests/nl/mod.rs
  text/tests/paste/mod.rs
  text/tests/pr/mod.rs
  text/tests/sort/mod.rs
  text/tests/tail/mod.rs
  text/tests/text-tests.rs
  text/tests/tr/mod.rs
  text/tests/unexpand-tests.rs
  text/tests/unexpand/mod.rs
  text/tests/uniq/mod.rs
  text/tests/wc/mod.rs
  tree/tests/link/mod.rs
  tree/tests/mkdir/mod.rs
  tree/tests/readlink/mod.rs
  tree/tests/rmdir/mod.rs
  tree/tests/tree-tests.rs
  tree/tests/unlink/mod.rs
  xform/tests/cksum/mod.rs
  xform/tests/compress/mod.rs
  xform/tests/uue/mod.rs
  xform/tests/xform-tests.rs
Labels: enhancement

#169 [find] first implementation
  Cargo.lock
  file/Cargo.toml
  file/src/find.rs
  file/tests/file-tests.rs
  file/tests/find/mod.rs
  file/tests/find/newer/.gitkeep
  file/tests/find/other/empty_file.txt
  file/tests/find/other/file with space.txt
  file/tests/find/other/file1.txt
  file/tests/find/other/rust_file.rs
Labels: enhancement

#161 [grep] first implementation
  text/Cargo.toml
  text/src/grep.rs
  text/tests/grep/bre/p_1
  text/tests/grep/bre/p_2
  text/tests/grep/empty_pattern
  text/tests/grep/ere/p_1
  text/tests/grep/ere/p_2
  text/tests/grep/f_1
  text/tests/grep/f_2
  text/tests/grep/f_3
  text/tests/grep/invalid_line
  text/tests/grep/mod.rs
  text/tests/text-tests.rs
Labels: enhancement

#170 Source flattening and cosmetics.
  Cargo.lock
  datetime/Cargo.toml
  datetime/cal.rs
  datetime/date.rs
  datetime/sleep.rs
  file/src/find.rs
  file/tests/file-tests.rs
  file/tests/find/mod.rs
  fs/Cargo.toml
  fs/df.rs
  misc/Cargo.toml
  misc/false.rs
  misc/test.rs
  misc/true.rs
  pathnames/Cargo.toml
  pathnames/basename.rs
  pathnames/dirname.rs
  pathnames/pathchk.rs
  text/src/grep.rs
Labels: cleanup

#171 Continue to flatten source tree
  dev/Cargo.toml
  dev/ar.rs
  dev/nm.rs
  dev/strings.rs
  dev/strip.rs
  display/Cargo.toml
  display/echo.rs
  display/printf.rs
  process/Cargo.toml
  process/env.rs
  process/kill.rs
  process/nice.rs
  process/nohup.rs
  process/renice.rs
  process/xargs.rs
  sccs/Cargo.toml
  sccs/what.rs
  screen/Cargo.toml
  screen/osdata.rs
  screen/stty.rs
  screen/tabs.rs
  screen/tput.rs
  sys/Cargo.toml
  sys/getconf.rs
  sys/ipcrm.rs
  sys/ipcs.rs
  sys/uname.rs
  sys/who.rs
  users/Cargo.toml
  users/id.rs
  users/logger.rs
  users/logname.rs
  users/mesg.rs
  users/pwd.rs
  users/tty.rs
  users/write.rs
  xform/Cargo.toml
  xform/cksum.rs
  xform/compress.rs
  xform/crc32.rs
  xform/uncompress.rs
  xform/uudecode.rs
  xform/uuencode.rs
Labels: cleanup

#172 Finish tree flatten
  tree/Cargo.toml
  tree/chgrp.rs
  tree/chmod.rs
  tree/chown.rs
  tree/common/mod.rs
  tree/cp.rs
  tree/du.rs
  tree/link.rs
  tree/ln.rs
  tree/ls.rs
  tree/ls_util/entry.rs
  tree/ls_util/mod.rs
  tree/ls_util/utf8_lossy.rs
  tree/mkdir.rs
  tree/mkfifo.rs
  tree/mv.rs
  tree/readlink.rs
  tree/rm.rs
  tree/rmdir.rs
  tree/touch.rs
  tree/unlink.rs
Labels: cleanup
