Repository rustcoreutils/posixutils-rs, pull requests merged in 2024-10, with the labels that each got.

#337 Cleanups
  i18n/iconv.rs
  i18n/tests/iconv/mod.rs
Labels: cleanup

#342 head: add -c option
  Cargo.lock
  plib/src/testing.rs
  text/Cargo.toml
  text/head.rs
  text/tests/head/mod.rs
Labels: enhancement

#333 diff: #[derive(Default)] and remove getter/setter
  text/diff_util/file_diff.rs
  text/diff_util/hunks.rs
Labels: enhancement

#349 readlink: implement -f
  tree/readlink.rs
  tree/tests/readlink/mod.rs
Labels: enhancement

#347 [newgrp] full implementation
  users/Cargo.toml
  users/newgrp.rs
Labels: enhancement

#357 small cargo cleanups
  Cargo.lock
  m4/test-manager/Cargo.toml
  m4/tests/integration_test.rs
Labels: cleanup

#358 Update README.md
  README.md
Labels: documentation
