Repository rustcoreutils/posixutils-rs, pull requests merged in 2024-09, with the labels that each got.

#213 clippy-inspired cleanups
  calc/expr.rs
  datetime/cal.rs
  datetime/date.rs
  dev/ar.rs
  display/echo.rs
  display/printf.rs
  file/dd.rs
  file/file.rs
  file/find.rs
  file/od.rs
  file/split.rs
  fs/df.rs
  ftw/src/lib.rs
  gettext-rs/src/lib.rs
  i18n/gencat.rs
  m4/test-manager/src/main.rs
  plib/src/io.rs
  plib/src/modestr.rs
  plib/src/sccsfile.rs
  process/env.rs
  process/kill.rs
  sccs/what.rs
  screen/stty.rs
  screen/tabs.rs
  sys/pslinux.rs
  sys/who.rs
  text/csplit.rs
  text/cut.rs
  text/expand.rs
  text/fold.rs
  text/grep.rs
  text/nl.rs
  text/paste.rs
  text/pr.rs
  text/pr_util/line_iterator.rs
  text/wc.rs
  tree/common/mod.rs
  tree/ls.rs
  tree/ls_util/entry.rs
  tree/mv.rs
  tree/rm.rs
  tree/touch.rs
  xform/compress.rs
  xform/uudecode.rs
  xform/uuencode.rs
Labels: cleanup

#216 ps: support -a, -e, -d options
  sys/ps.rs
  sys/pslinux.rs
  sys/psmacos.rs
Labels: enhancement

#229 Musl merge: priority APIs
  Cargo.lock
  m4/Cargo.toml
  plib/Cargo.toml
  plib/src/lib.rs
  plib/src/priority.rs
  process/Cargo.toml
  process/renice.rs
Labels: enhancement

#191 [fuser] full implementation
  Cargo.lock
  process/Cargo.toml
  process/build.rs
  process/fuser.rs
  process/tests/fuser/mod.rs
  process/tests/process-tests.rs
Labels: enhancement

#232 [plib] new platform module, for OS and libc abstraction
  plib/src/lib.rs
  plib/src/platform.rs
  plib/src/utmpx.rs
  sys/who.rs
  tree/ls.rs
  users/write.rs
Labels: enhancement

#233 plib/testing: improve test executor: large inputs, early exits
  plib/src/testing.rs
Labels: bug

#234 plib/testing: cleanups
  plib/src/testing.rs
Labels: cleanup

#249 PS: flexible output field selection
  fs/df.rs
  process/tests/fuser/mod.rs
  sys/ps.rs
Labels: enhancement

#250 ps: cleanups
  sys/ps.rs
Labels: cleanup

#253 Cleanups
  dev/ar.rs
  dev/nm.rs
  dev/strings.rs
  file/dd.rs
  file/find.rs
  m4/test-manager/src/main.rs
  plib/src/utmpx.rs
  text/csplit.rs
  text/cut.rs
  text/diff.rs
  text/diff_util/common.rs
  text/diff_util/file_data.rs
  text/diff_util/file_diff.rs
  text/diff_util/hunks.rs
  text/fold.rs
  text/nl.rs
  text/pr_util/args.rs
  text/tail.rs
  text/tr.rs
  xform/uudecode.rs
Labels: cleanup

#227 [timeout] full implementation, 3d iteration
  Cargo.lock
  process/Cargo.toml
  process/tests/process-tests.rs
  process/tests/timeout/mod.rs
  process/tests/timeout/non_executable.sh
  process/tests/timeout/spawn_child.sh
  process/tests/timeout/with_argument.sh
  process/timeout.rs
Labels: enhancement

#255 timeout: cleanups
  README.md
  process/timeout.rs
Labels: cleanup

#262 Cargo: shared workspace metadata
  Cargo.toml
  awk/Cargo.toml
  calc/Cargo.toml
  datetime/Cargo.toml
  dev/Cargo.toml
  display/Cargo.toml
  file/Cargo.toml
  fs/Cargo.toml
  ftw/Cargo.toml
  gettext-rs/Cargo.toml
  i18n/Cargo.toml
  m4/Cargo.toml
  m4/test-manager/Cargo.toml
  misc/Cargo.toml
  pathnames/Cargo.toml
  plib/Cargo.toml
  process/Cargo.toml
  sccs/Cargo.toml
  screen/Cargo.toml
  sys/Cargo.toml
  text/Cargo.toml
  tree/Cargo.toml
  users/Cargo.toml
  xform/Cargo.toml
Labels: cleanup

#263 Cleanups
  Cargo.lock
  users/talk.rs
Labels: cleanup

#265 Cleanups
  file/dd.rs
  file/file.rs
  file/split.rs
  misc/test.rs
  plib/src/lzw.rs
  screen/stty.rs
  text/asa.rs
  text/expand.rs
  text/head.rs
  text/pr_util/args.rs
  text/wc.rs
  users/mesg.rs
  xform/cksum.rs
  xform/crc32.rs
Labels: cleanup
